services:
  app:
    image: phonebook-frontend-dev
    volumes:
      - ./frontend/:/usr/src/app
    container_name: phonebook-frontend-dev

  server:
    image: phonebook-backend-dev
    volumes:
      - ./backend/:/usr/src/app
    container_name: phonebook-backend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server